// src/components/AnalyticsTab.jsx
import React, { useState } from 'react';

export default function AnalyticsTab({ data }) {
  const [filter, setFilter] = useState('ALL');

  if (!data || data.length === 0) {
    return (
      <div className="card" style={{ textAlign: 'center', padding: '3rem' }}>
        <h3 style={{ fontSize: '1.125rem', marginBottom: '0.5rem' }}>No Evaluated Data Available</h3>
        <p style={{ fontSize: '0.875rem', color: 'var(--text-subtle)', maxWidth: '400px', margin: '0 auto' }}>
          Navigate to the Social Ingestion tab to extract comments and trigger batch transformer analysis.
        </p>
      </div>
    );
  }

  // Use the REAL values generated by your FastAPI backend (no hardcoded overrides)
  const processed = data.map((item) => {
    // Normalise label formatting (Positive, Negative, Neutral, Mixed, Unsupported)
    const rawLabel = item.sentiment || item.label || 'Neutral';
    const label = rawLabel.charAt(0).toUpperCase() + rawLabel.slice(1).toLowerCase();

    return {
      id: item.id || item.comment_id,
      author: item.author || '@anonymous',
      text: item.text || item.comment || '',
      // Real dynamic translation from backend GoogleTranslationService
      translation: item.translation || item.translated_text || item.text,
      label: label,
      confidence: item.confidence ?? 0,
      isSupported: item.is_supported ?? (label !== 'Unsupported'),
      likes: item.likes ?? item.like_count ?? 0,
      date: item.date || item.published_at || 'Recent'
    };
  });

  const total = processed.length;
  const supportedCount = processed.filter((c) => c.isSupported).length;
  const posCount = processed.filter((c) => c.label === 'Positive').length;
  const negCount = processed.filter((c) => c.label === 'Negative').length;
  const neuCount = processed.filter((c) => c.label === 'Neutral').length;
  const mixCount = processed.filter((c) => c.label === 'Mixed').length;

  const posPct = total > 0 ? Math.round((posCount / total) * 100) : 0;
  const negPct = total > 0 ? Math.round((negCount / total) * 100) : 0;
  const neuPct = total > 0 ? Math.round((neuCount / total) * 100) : 0;
  const nss = posPct - negPct;

  const filteredComments = processed.filter((c) => {
    if (filter === 'ALL') return true;
    return c.label.toUpperCase() === filter;
  });

  return (
    <div>
      {/* KPI Cards Header */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: '1rem',
        marginBottom: '1.5rem'
      }}>
        <div className="card" style={{ marginBottom: 0 }}>
          <div style={{ fontSize: '0.6875rem', fontWeight: '700', color: 'var(--text-subtle)', fontFamily: 'var(--font-mono)' }}>
            TOTAL EVALUATED
          </div>
          <div style={{ fontSize: '1.75rem', fontWeight: '800', marginTop: '0.25rem' }}>
            {total}
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-subtle)' }}>
            Supported: {supportedCount}
          </div>
        </div>

        <div className="card" style={{ marginBottom: 0 }}>
          <div style={{ fontSize: '0.6875rem', fontWeight: '700', color: 'var(--pos-color)', fontFamily: 'var(--font-mono)' }}>
            POSITIVE RATIO
          </div>
          <div style={{ fontSize: '1.75rem', fontWeight: '800', color: 'var(--pos-color)', marginTop: '0.25rem' }}>
            {posPct}%
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-subtle)' }}>
            {posCount} comments
          </div>
        </div>

        <div className="card" style={{ marginBottom: 0 }}>
          <div style={{ fontSize: '0.6875rem', fontWeight: '700', color: 'var(--neg-color)', fontFamily: 'var(--font-mono)' }}>
            NEGATIVE RATIO
          </div>
          <div style={{ fontSize: '1.75rem', fontWeight: '800', color: 'var(--neg-color)', marginTop: '0.25rem' }}>
            {negPct}%
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-subtle)' }}>
            {negCount} comments
          </div>
        </div>

        <div className="card" style={{ marginBottom: 0 }}>
          <div style={{ fontSize: '0.6875rem', fontWeight: '700', color: 'var(--neu-color)', fontFamily: 'var(--font-mono)' }}>
            NET SENTIMENT SCORE (NSS)
          </div>
          <div style={{ fontSize: '1.75rem', fontWeight: '800', marginTop: '0.25rem' }}>
            {nss > 0 ? `+${nss}` : nss}
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-subtle)' }}>
            Scale: -100 to +100
          </div>
        </div>
      </div>

      {/* Aggregate Distribution Bar */}
      <div className="card">
        <div className="card-header">
          <div className="card-title">Continuous Class Projections</div>
          <div className="card-subtitle">Aggregate polarity distribution calculated across the verified comment batch</div>
        </div>
        <div className="progress-track" style={{ height: '14px', marginBottom: '0.75rem' }}>
          <div className="progress-fill-pos" style={{ width: `${posPct}%` }} title={`Positive: ${posPct}%`} />
          <div className="progress-fill-neg" style={{ width: `${negPct}%` }} title={`Negative: ${negPct}%`} />
          <div className="progress-fill-neu" style={{ width: `${neuPct}%` }} title={`Neutral: ${neuPct}%`} />
        </div>
        <div style={{ display: 'flex', gap: '1.5rem', fontSize: '0.75rem', fontFamily: 'var(--font-mono)' }}>
          <span style={{ display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
            <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: 'var(--pos-color)' }} />
            Positive ({posPct}%)
          </span>
          <span style={{ display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
            <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: 'var(--neg-color)' }} />
            Negative ({negPct}%)
          </span>
          <span style={{ display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
            <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: 'var(--neu-color)' }} />
            Neutral ({neuPct}%)
          </span>
        </div>
      </div>

      {/* Filter Matrix Controls & Data Stream */}
      <div className="card">
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: '1rem',
          flexWrap: 'wrap',
          gap: '0.5rem'
        }}>
          <div>
            <div className="card-title">Curated Analysis Stream</div>
            <div className="card-subtitle">Showing {filteredComments.length} of {total} records</div>
          </div>

          <div style={{ display: 'flex', gap: '0.25rem', backgroundColor: 'var(--bg-subtle)', padding: '0.25rem', borderRadius: '6px' }}>
            {['ALL', 'POSITIVE', 'MIXED', 'NEUTRAL', 'NEGATIVE', 'UNSUPPORTED'].map((tab) => (
              <button
                key={tab}
                onClick={() => setFilter(tab)}
                style={{
                  border: 'none',
                  background: filter === tab ? '#ffffff' : 'transparent',
                  color: filter === tab ? 'var(--text-main)' : 'var(--text-muted)',
                  fontWeight: filter === tab ? '700' : '500',
                  fontSize: '0.6875rem',
                  padding: '0.25rem 0.5rem',
                  borderRadius: '4px',
                  cursor: 'pointer',
                  fontFamily: 'var(--font-mono)',
                  boxShadow: filter === tab ? '0 1px 2px rgba(0,0,0,0.05)' : 'none'
                }}
              >
                {tab}
              </button>
            ))}
          </div>
        </div>

        {/* Comment Rows */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          {filteredComments.map((c, i) => (
            <div key={c.id || i} style={{
              padding: '0.875rem 1rem',
              backgroundColor: 'var(--bg-subtle)',
              borderRadius: '8px',
              border: '1px solid var(--border-color)'
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.375rem' }}>
                <span style={{ fontWeight: '700', fontSize: '0.8125rem' }}>{c.author}</span>
                <span className={`badge ${
                  c.label === 'Positive' ? 'badge-pos' : 
                  c.label === 'Negative' ? 'badge-neg' : 
                  c.label === 'Mixed' ? 'badge-slate' : 
                  c.label === 'Unsupported' ? 'badge-neg' : 'badge-neu'
                }`}>
                  {c.label} {c.confidence > 0 && `(${c.confidence}%)`}
                </span>
              </div>
              <p style={{ fontSize: '0.875rem', marginBottom: '0.375rem', color: 'var(--text-main)' }}>
                "{c.text}"
              </p>
              <div style={{ fontSize: '0.75rem', fontStyle: 'italic', color: 'var(--text-muted)' }}>
                Translation: "{c.translation}"
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}